[
 {
  "author": "hwright", 
  "date": "2010-11-09T20:55:44.622448Z", 
  "msg": [
   "Reintegrate the 1.6.x-r991534 branch:", 
   "* r991534", 
   "Fix random test failures when tests are run in parallel over DAV.", 
   "Justification:", 
   "Random test failures irritate developers trying to do release", 
   "testing. See also the r877814 backport.", 
   "Backport branch:", 
   "^/subversion/branches/1.6.x-r991534", 
   "Votes:", 
   "+1: stsp, cmpilato, hwright"
  ], 
  "revision_id": "1033220"
 }, 
 {
  "author": "hwright", 
  "date": "2010-11-09T20:53:07.542144Z", 
  "msg": [
   "Remove the 1.6.x-r877814 branch, reintegrated in r1033217."
  ], 
  "revision_id": "1033219"
 }, 
 {
  "author": "stsp", 
  "date": "2010-11-09T20:52:40.539294Z", 
  "msg": [
   "* STATUS (for 1.5.x): Nominate r1033166."
  ], 
  "revision_id": "1033218"
 }, 
 {
  "author": "hwright", 
  "date": "2010-11-09T20:52:34.573650Z", 
  "msg": [
   "Reintegrate the 1.6.x-r877814 branch:", 
   "* r877814", 
   "Fix random test failures in merge_tests.py when tests are run in parallel.", 
   "Justification:", 
   "I lost a few hours tracking down test failures during 1.6.13 release", 
   "testing. Once I found out what was going on I realised this had", 
   "already been fixed on trunk. Let's not have anyone waste their time", 
   "on this again.", 
   "Backport branch:", 
   "^/subversion/branches/1.6.x-r877814", 
   "Votes:", 
   "+1: stsp, cmpilato, hwright"
  ], 
  "revision_id": "1033217"
 }, 
 {
  "author": "hwright", 
  "date": "2010-11-09T20:50:43.743667Z", 
  "msg": [
   "Remove the 1.6.x-issue3727 branch, reintegrated in r1033215."
  ], 
  "revision_id": "1033216"
 }
]