[
 {
  "author": "jleroux", 
  "date": "2011-03-25T23:55:24.920233Z", 
  "msg": [
   "Forgot a \"m\" in previous commit"
  ], 
  "revision_id": "1085605"
 }, 
 {
  "author": "lu4242", 
  "date": "2011-03-25T23:50:17.084679Z", 
  "msg": [
   "[maven-release-plugin] prepare branch 2.1.x"
  ], 
  "revision_id": "1085604"
 }, 
 {
  "author": "lu4242", 
  "date": "2011-03-25T23:49:15.194710Z", 
  "msg": [
   "revert bad branch creation"
  ], 
  "revision_id": "1085603"
 }, 
 {
  "author": "danielsh", 
  "date": "2011-03-25T23:47:13.462539Z", 
  "msg": [
   "* subversion/tests/cmdline/tree_conflict_tests.py", 
   "(at_directory_external): New XFail test for issue #3469.", 
   "(test_list): Run it."
  ], 
  "revision_id": "1085602"
 }, 
 {
  "author": "danielsh", 
  "date": "2011-03-25T23:45:04.700627Z", 
  "msg": [
   "* subversion/tests/cmdline/svntest/main.py", 
   "(youngest): New helper."
  ], 
  "revision_id": "1085601"
 }
]