[
 {
  "author": "alexparvulescu", 
  "date": "2015-02-20T14:00:04.011224Z", 
  "msg": [
   "OAK-2541 TARMK Cold Standby marks the sync as stopped on first error", 
   "- merged r1661122"
  ], 
  "revision_id": "1661123"
 }, 
 {
  "author": "alexparvulescu", 
  "date": "2015-02-20T13:57:48.226176Z", 
  "msg": [
   "OAK-2541 TARMK Cold Standby marks the sync as stopped on first error"
  ], 
  "revision_id": "1661122"
 }, 
 {
  "author": "rhuijben", 
  "date": "2015-02-20T13:56:13.340224Z", 
  "msg": [
   "Following up on r1661120 and a whole lot of previous attempts fix issue #4467.", 
   "* subversion/libsvn_client/blame.c", 
   "(file_rev_handler): Get rid of assertion that doesn't really make sense now.", 
   "(It would have required an additional exception that would let half the", 
   "interesting cases get through)", 
   "* subversion/tests/cmdline/blame_tests.py", 
   "(blame_reverse_no_change): Remove XFail marker. Add comments."
  ], 
  "revision_id": "1661121"
 }, 
 {
  "author": "rhuijben", 
  "date": "2015-02-20T13:52:59.426697Z", 
  "msg": [
   "Add a regression test for issue #4467, to finally get to the bottom", 
   "of this problem.", 
   "* subversion/tests/cmdline/blame_tests.py", 
   "(blame_reverse_no_change): New function.", 
   "(test_list): Add blame_reverse_no_change."
  ], 
  "revision_id": "1661120"
 }, 
 {
  "author": "julianfoad", 
  "date": "2015-02-20T13:43:30.955086Z", 
  "msg": [
   "* STATUS: Veto r1660969, assertion in reverse blame."
  ], 
  "revision_id": "1661119"
 }
]