[
 {
  "author": "cmpilato", 
  "date": "2003-09-30T18:08:57.926524Z", 
  "msg": [
   "Finish issue #1519 - 'svn up doesn't fetch modifications after", 
   "svn:externals URL has been changed'.", 
   "* subversion/libsvn_client/externals.c", 
   "(handle_external_item_change): For unchanged externals definitions,", 
   "we now check to see if the thing on disk matches the definition.  If", 
   "not, we re-checkout."
  ], 
  "revision_id": "847330"
 }, 
 {
  "author": "cmpilato", 
  "date": "2003-09-30T14:23:06.436917Z", 
  "msg": [
   "* subversion/libsvn_fs/txn.c", 
   "(txn_body_abort_txn): Bail out immediately if someone is trying to", 
   "abort a committed Subversion transaction, instead of doing all the", 
   "work of cleaning up the Subversion transaction only to be denied", 
   "the removal the thing itself at the end of the function.  NOTE:", 
   "because we do all this cleanup in a single Berkeley transaction,", 
   "this is not a correctness fix -- a failure at Subversion", 
   "transaction time in the past would have resulted in none of the", 
   "cleanups \"going live\".  But what a waste of time..."
  ], 
  "revision_id": "847329"
 }, 
 {
  "author": "maxb", 
  "date": "2003-09-30T14:12:01.046158Z", 
  "msg": [
   "* tools/cvs2svn/run-tests.py: Update revision numbers to deal with extra empty", 
   "revision caused by the changes of r7253."
  ], 
  "revision_id": "847328"
 }, 
 {
  "author": "maxb", 
  "date": "2003-09-30T13:52:11.701273Z", 
  "msg": [
   "Fix issue 1529.", 
   "* tools/cvs2svn/cvs2svn.py (Commit.commit): Do not erroneously special-case", 
   "deletion of cvs rev 1.1 - it is *not* a guarantee that there are no previous", 
   "revisions."
  ], 
  "revision_id": "847327"
 }, 
 {
  "author": "maxb", 
  "date": "2003-09-30T13:40:13.709313Z", 
  "msg": [
   "Revert revisions 7246 and 7247. These were from a partial committer outside", 
   "their designated area, and caused many testsuite failures."
  ], 
  "revision_id": "847326"
 }
]