[
 {
  "author": "kameshj", 
  "date": "2007-07-04T18:50:49.805858Z", 
  "msg": [
   "Fix the problem: Two people from 2 different working copies at revision rX", 
   "trying to do a merge of rY and rZ independently from /branch/b1 to /trunk.", 
   "Assume the first person commits(merge of rY), when second guy tries to", 
   "do the commit(merge of rZ) he would get a out of date error. So second", 
   "guy would do 'svn up'. svn up does not merge the 'svn:mergeinfo' correctly", 
   "It just keeps rZ.", 
   "* subversion/libsvn_wc/props.c", 
   "(svn_wc__merge_props): Record the merged svn:mergeinfo on the target.", 
   "Found by: Piet-Hein Peeters", 
   "Reviewed by: dlr"
  ], 
  "revision_id": "865720"
 }, 
 {
  "author": "sage", 
  "date": "2007-07-04T03:17:43.657348Z", 
  "msg": [
   "Add resolved method to python WC class. The resolved", 
   "method works just like svn_client_resolved() (in fact,", 
   "it calls that function).", 
   "* csvn/wc.py", 
   "(resolved): New method to mark a conflict as resolved."
  ], 
  "revision_id": "865719"
 }, 
 {
  "author": "lgo", 
  "date": "2007-07-03T21:42:39.536932Z", 
  "msg": [
   "* STATUS: Nominate r25640, -41 for inclusion in the fix for issue #2804", 
   "Vote for the whole group."
  ], 
  "revision_id": "865718"
 }, 
 {
  "author": "lgo", 
  "date": "2007-07-03T21:37:46.258127Z", 
  "msg": [
   "Merge r25640, -41 from trunk. These add an extra regression test for this fix.", 
   "* subversion/tests/cmdline/revert_tests.py", 
   "(status_of_missing_dir_after_revert_replaced_with_history_dir): new test", 
   "(test_list): run the new test"
  ], 
  "revision_id": "865717"
 }, 
 {
  "author": "sage", 
  "date": "2007-07-03T21:28:22.010131Z", 
  "msg": [
   "Add export functionality to python WC class. Based on", 
   "svn_client_export3(), but designed to export the", 
   "working copy, not anything else.", 
   "* csvn/wc.py", 
   "(export): New method to export the working copy."
  ], 
  "revision_id": "865716"
 }
]