[
 {
  "author": "julianfoad", 
  "date": "2008-05-21T13:24:59.216158Z", 
  "msg": [
   "Destroy a sub-pool after use. A follow-up to r31326 which introduced it.", 
   "* subversion/libsvn_client/merge.c", 
   "(merge_dir_opened): Destroy the subpool."
  ], 
  "revision_id": "871405"
 }, 
 {
  "author": "pburba", 
  "date": "2008-05-21T13:15:35.111234Z", 
  "msg": [
   "* STATUS: Nominate r31300, r31301, r31312 group."
  ], 
  "revision_id": "871404"
 }, 
 {
  "author": "julianfoad", 
  "date": "2008-05-21T13:08:58.258449Z", 
  "msg": [
   "Make test 7 in tree_conflict_tests.py pass. It was failing because of getting", 
   "two conflicts at once, for the source and the destination of a move, when we", 
   "only wanted to test a conflict on the source of the move.", 
   "* subversion/tests/cmdline/tree_conflict_tests.py", 
   "(incoming_paths, localmod_paths): New functions.", 
   "(modify): Take a dictionary of paths to use, rather than constructing the", 
   "set of paths internally, so that different paths can be used for the", 
   "target of a 'move' operation in the incoming and the localmod scenarios.", 
   "(set_up): Adjust calls to modify() accordingly.", 
   "(ensure_tree_conflict): Adjust calls to modify() accordingly. Use", 
   "run_and_verify_svn() instead of run_svn(), and remove some verbosity that", 
   "is now handled within those run_* functions."
  ], 
  "revision_id": "871403"
 }, 
 {
  "author": "julianfoad", 
  "date": "2008-05-21T12:58:55.620130Z", 
  "msg": [
   "Fix run_command_stdin()'s printing of stderr which I broke in r31326.", 
   "* subversion/tests/cmdline/svntest/main.py", 
   "(run_command_stdin): Print stderr if an error occurs, not just when", 
   "running in verbose mode."
  ], 
  "revision_id": "871402"
 }, 
 {
  "author": "julianfoad", 
  "date": "2008-05-21T11:26:32.594234Z", 
  "msg": [
   "Fix some tests that were failing due to tree conflict handling.", 
   "Tests 10 and 11 of blame_tests.py, and 16 17 18 19 of log_tests.py, now pass.", 
   "* subversion/tests/cmdline/log_tests.py", 
   "(merge_history_repos): Resolve a tree conflict that was causing this set-up", 
   "function to fail."
  ], 
  "revision_id": "871401"
 }
]